disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - type_name
  - nesting
  - function_parameter_count
  - function_body_length
  - multiple_closures_with_trailing_closure
  - class_delegate_protocol
  - empty_enum_arguments
  - large_tuple
  - trailing_whitespace

opt_in_rules:
  - control_statement
  - trailing_newline
  - colon
  - comma
  - force_try
  - force_cast
  - force_unwrapping

excluded:
  - Pods
  - SwiftLint/Common/3rdPartyLib
  - Project/R.generated.swift
  - vendor/bundle

#included: # paths to include during linting. `--path` is ignored if present.
  - TrueCoach
  - TrueCoachTests
#  # - ProjectUITests

custom_rules:
  disable_print:
    included: ".*\\.swift"
    name: "print statement usage"
    regex: "((\\bprint)|(Swift\\.print))\\s*\\("
    message: "Prefer os_log over print"
    severity: warning

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: error
force_try: error
force_unwrapping: error
shorthand_operator: warning

#large_tuple:
#    severity: warning

line_length:
    warning: 500
    error: 1000
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

# function_body_length:
#     warning: 300
#     error: 500

# function_parameter_count:
#     warning: 6
#     error: 8

type_body_length:
    warning: 400
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
# type_name:
#   min_length: 4 # only warning
#   max_length: # warning and error
#     warning: 30
#     error: 35
  # excluded: iPhone # excluded via string
reporter: "xcode"
